### ISSUE TITLE
Missing initializer

### ISSUE THREAD

**Issue by antoscha** [Akimkin/kf5-kio-ftps#3]
```
kf5-kio-ftps-0.3/ftp.cpp:147:27: error: expected initializer before ‘kdemain’
  147 | extern "C" int KDE_EXPORT kdemain( int argc, char **argv )
      |
```

**Comment by Akimkin** [comment]
What is the build environment (OS, compiler, KDE Frameworks versions)?

**Comment by antoscha** [comment]
Arch Linux, GCC 10.2, KF5 5.74.1

**Comment by Akimkin** [comment]
Please try to build now. I don't have access to any build environment at the moment, but my quick-fix attempt may work.

**Comment by antoscha** [comment]
Works like a magic! Thanks!
